### ISSUE TITLE
DLL load failed while importing diffvg

### ISSUE THREAD

**Issue by Lqy200004** [WordAsImage/Word-As-Image#9]
hello,when I run "python code/main.py --semantic_concept "BUNNY" --optimized_letter "Y" --font "KaushanScript-Regular" --seed 0",there raise some error:

(word) F:\Code\Word-As-Image>python code/main.py --semantic_concept "BUNNY" --optimized_letter "Y" --font "KaushanScript-Regular" --seed 0
Traceback (most recent call last):
File "code/main.py", line 8, in
import pydiffvg
File "F:\Code\Anaconda\envs\word\lib\site-packages\diffvg-0.0.1-py3.8-win-amd64.egg\pydiffvg_init_.py", line 4, in
from .render_pytorch import *
File "F:\Code\Anaconda\envs\word\lib\site-packages\diffvg-0.0.1-py3.8-win-amd64.egg\pydiffvg\render_pytorch.py", line 2, in
import diffvg
ImportError: DLL load failed while importing diffvg:

I think it may diffvg problem?How can i resolve that.

Does he have to work on linux, please?

**Comment by bennedik** [comment]
On a Windows machine, I'm getting this error:

Traceback (most recent call last):
  File "code/main.py", line 8, in <module>
    import pydiffvg
ModuleNotFoundError: No module named 'pydiffvg'

When I try to build the diffvg, there is also an error message.

**Comment by Lqy200004** [comment]
> 

Ok,thanks.I'll try to see if the project will work on linux.

**Comment by nicolai256** [comment]
I had a lot of issues with this too yesterday, it's best to use visual studio 2017 for building it, 
also after you've built it you need to rename 
F:\Code\Anaconda\envs\word\lib\site-packages\diffvg-0.0.1-py3.8-win-amd64.egg\diffvg 
to 
F:\Code\Anaconda\envs\word\lib\site-packages\diffvg-0.0.1-py3.8-win-amd64.egg\diffvg.pyd

then it should work, also make sure you're actually installing everything in conda (so make sure conda is in PATH)
yesterday some of the installs were not installing into my conda env but to my other python and that gave me lots of issues

**Comment by Lqy200004** [comment]
> I had a lot of issues with this too yesterday, it's best to use visual studio 2017 for building it (2019 works too but you need to change some code), 
> also after you've built it you need to rename 
> F:\Code\Anaconda\envs\word\lib\site-packages\diffvg-0.0.1-py3.8-win-amd64.egg\diffvg 
> to 
> F:\Code\Anaconda\envs\word\lib\site-packages\diffvg-0.0.1-py3.8-win-amd64.egg\diffvg.pyd
> 
> then it should work, also make sure you're actually installing everything in conda (so make sure conda is in PATH)
> yesterday some of the installs were not installing into my conda env but to my other python and that gave me lots of issues

Thanks,nicolai,I try to run this code on ubuntu,that works without problem.I'll use your method to see if I can run this program on Windows.

**Comment by Shehjad-Ishan** [comment]
> I had a lot of issues with this too yesterday, it's best to use visual studio 2017 for building it (2019 works too but you need to change some code), also after you've built it you need to rename F:\Code\Anaconda\envs\word\lib\site-packages\diffvg-0.0.1-py3.8-win-amd64.egg\diffvg to F:\Code\Anaconda\envs\word\lib\site-packages\diffvg-0.0.1-py3.8-win-amd64.egg\diffvg.pyd
> 
> then it should work, also make sure you're actually installing everything in conda (so make sure conda is in PATH) yesterday some of the installs were not installing into my conda env but to my other python and that gave me lots of issues

I am getting DLL import error when I change to .pyd
